### ISSUE TITLE
Cant add more then 2 homes.

### ISSUE THREAD

**Issue by Duqino** [Thutmose/ThutEssentials#32]
Hello,

Im trying to give everyone some extra homes, but somehow it doenst work....
Not sure if im doing something wrong.

https://pastebin.com/eWwMD0fP

ftbutilities.homes.max
ftbutilities.homes.10

Kind regards,

Duqino.

**Comment by Thutmose** [comment]
this issue should probably be over in thutperms instead, if you are using ftbutilities, you should probably be using it for permissions rather than thutperms though.

**Comment by Duqino** [comment]
If thutperms was working fine.... But its not. Then i have no problems using thutperms.

And im so damn stupid...... Used the wrong perms.....

And as far as i know i cant add more homes for other ranks.

**Comment by Thutmose** [comment]
I haven't tested the permissions for other mod things very much, so I am not entirely sure what is going on, or what should be going on.  If you do need help with it, can you make an issue over here https://github.com/Thutmose/ThutPerms/issues 
including what you have tried, what you think should work, and what is actually happening?

I am closing this particular issue, as it really should be on that other issue tracker, rather than here

**Comment by ghost** [comment]
Can't add more than 2 home too.
I'm installed ThutEssentials + Twilightforest MOD only
How to add more home?
